# Grunt aliases
---
'build':
  - 'build:js'

# Build JavaScript from assets to production
'build:js':
  - 'clean:build-assets'
  - 'webpack:buildDev'

clean:build-assets:
  - 'clean:build-assets-js'

# Update all versions except the stable tag
'update-version-trunk':
  - 'update-version:pluginFile'
  - 'update-version:initializer'

# Default task
default:
  - 'build'
