# These are supported funding model platforms

github: enricobattocchi
ko_fi: duplicatepost
liberapay: lopo
patreon: duplicatepost
custom: ['https://www.paypal.me/lopo', 'https://duplicate-post.lopo.it/donate/']
