os: linux
language: php

branches:
  only:
    - master
    - develop
    - /^release\/*/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^feature\/*/
    # Also build tags like 1.1.1 or 1.1 for deployment.
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - .cache
    - $HOME/.composer/cache

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0'
    - "nightly"

jobs:
  fast_finish: true
  include:
    # Arbitrary PHP version to run the sniffs against.
    - php: '7.4'
      env: SNIFF=1 PHPUNIT=1

  allow_failures:
    - php: "nightly"

before_install:
  - if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} == "8" || $TRAVIS_PHP_VERSION == "nightly" ]]; then
      travis_retry composer install --ignore-platform-reqs
    else
      travis_retry composer install
    fi


before_script:
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

script:
  - composer lint
  - if [[ "$SNIFF" == "1" ]]; then composer check-cs; fi
  - if [[ "$SNIFF" == "1" ]]; then composer check-vip; fi
  # PHP Unit Tests
  - |
    if [[ "$PHPUNIT" == "1" ]]; then
      travis_fold start "PHP.tests" && travis_time_start
      composer test
      travis_time_finish && travis_fold end "PHP.tests"
    fi
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then composer validate --no-check-all; fi
